sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "docker-react-2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-205368330264"
  build_path: "docker-react-2"
  on:
    branch: master