sudo: required
services: 
  - docker

before_install:
  - docker build -t docker-multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true docker-multi npm run test -- --coverage

after_success:
  - docker build -t ben/multi-client ./client
  - docker build -t ben/multi-server ./server
  - docker build -t ben/multi-nginx ./ngnix
  - docker build -t ben/multi-worker ./worker